apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-backend
  labels:
    app: school-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-backend
  template:
    metadata:
      labels:
        app: school-backend
    spec:
      containers:
      - name: nodejs-api
        image: docker.io/yourusername/school-backend:poc
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://admin:password123@school-db-service:5432/school_portal"